version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: system-adapter
    ldflags:
      - -X main.version={{.Version}}

archives:
  - formats: [ "tar.gz" ]
    # Use zip for Windows binaries automatically
    format_overrides:
      - goos: windows
        formats: [ "zip" ]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE.md
      - config/system-adapter.yaml
      - journal/.gitignore
      - log/.gitignore
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"